#!/bin/bash
# Quick Analytics Setup Script
# Usage: bash setup-analytics.sh

echo "🔧 Dosnine Analytics Setup"
echo "========================="
echo ""
echo "This script will guide you through setting up analytics."
echo ""
echo "Step 1: Database Migration"
echo "  ✓ Migration SQL file created at: starter/supabase-analytics-migration.sql"
echo "  → Go to Supabase → SQL Editor"
echo "  → Copy-paste contents of starter/supabase-analytics-migration.sql"
echo "  → Click Run"
echo ""
echo "Step 2: Environment Variables"
echo "  Create starter/.env.local with:"
echo ""
echo "    NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co"
echo "    NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key"
echo "    SUPABASE_SERVICE_ROLE_KEY=your-service-role-key"
echo ""
echo "  Find keys in: Supabase → Settings → API"
echo ""
echo "Step 3: Restart Server"
echo "  cd starter"
echo "  npm run dev"
echo ""
echo "Step 4: Test (Optional)"
echo "  # Check if table exists"
echo "  SUPABASE_SERVICE_ROLE_KEY=your_key node check-analytics-setup.js check"
echo ""
echo "  # Insert test data"
echo "  SUPABASE_SERVICE_ROLE_KEY=your_key node check-analytics-setup.js insert-test"
echo ""
echo "Step 5: View Analytics"
echo "  → Open http://localhost:3000/admin/analytics"
echo "  → Click 'Refresh' to see data"
echo ""
echo "📖 Full guide: starter/ANALYTICS_SETUP.md"
